version: '2'

services:
  dotnetcoredemoapp:
    image: username/dotnetcoredemoapp:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
